# Hibernate datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miraclebank_db?useSSL=false
    username: new-user
    password: password

  # JPA configurations
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: MYSQL
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL57Dialect

# Logging configurations
logging:
  level:
    root: WARN
    com.memorynotfound: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

